name: '[Support] Synchronize labels from the containers repository'
on:
  workflow_dispatch:
permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          source-repo: bitnami/containers
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}
